
version = "1.0.4-main.0"

# hugo config
baseURL: "https://wehwan.github.io/docs-auto-test/"
languageCode: "en-us"
title: "RPS Document Site Test"
theme: "hugo-book"

# hugo-book theme config
params:
  BookTheme: auto
  BookSection: "*"
