name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
      
      # copy files 1
#       - uses: actions/checkout@master
#       - name: copy file
#         uses: canastro/copy-file-action@master
#         with:
#           source: "./submodules"
#           target: "./content/submodules"

      # copy files 2
      - name: Copy Paste Action
        uses: ShreyamMaity/Copy-Paste-Action@main
        with:
          TOKEN: ${{ secrets.TOKEN }}
          REPOSITORY : wehwan/docs-auto-test
          COPY-FILE-LOCATION : './submodules'
          PASTE-FILE-LOCATION : './content/submodules'
