name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
      
      # copy files
      - uses: actions/checkout@master
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "submodules"
          target: "content/submodules"
